apiVersion: v1
kind: Service
metadata:
  name: sensor-relay
spec:
  ports:
  - name: http
    port: 8967
    protocol: TCP
    targetPort: 8967
  selector:
    app: sensor-relay
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor-relay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensor-relay
  template:
    metadata:
      labels:
        app: sensor-relay
    spec:
      containers:
      - image: $DOCKER_IMAGE
        imagePullPolicy: Always
        name: sensor-relay-container
        env:
        - name: MQTT_HOST
          value: $MQTT_HOST
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: sensor-relay
  namespace: default
spec:
  rules:
    - host: sensor-relay.int.mindphaser.se
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sensor-relay
                port:
                  number: 8967

